name: noahsark
favicon: null
layout_spectrum: 0.48096293257549405
typography_spectrum: 0.8598329585511237
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.9170436353888363
  lightness: 0.4310451054479927
  saturation: 0.7281221065204591
  rhythmicContrast: 0.10229225130751729
purpose: []
